name: Compute latest website and CV document
  
on:
  push:
    branches:
      - '**'
      
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python3 --version
        python -m pip install --upgrade pip
        pip install -r generate-cv/requirements.txt
    - name: Run main
      run: |
        python3 --version
        cd generate-cv/
        python3 main.py
    - name: Generate PDFs
      run: |
          brew install --cask libreoffice
          pwd
          cd generate-cv/
          ls -al *.docx
          mv cv-long-nelly-barret.pdf cv-long-nelly-barret-old.pdf
          mv cv-short-nelly-barret.pdf cv-short-nelly-barret-old.pdf
          soffice --headless --convert-to pdf:writer_pdf_Export cv-long-nelly-barret.docx
          soffice --headless --convert-to pdf:writer_pdf_Export cv-short-nelly-barret.docx
    - name: Push generated CVs
      run: |
          git config --global user.name 'Nelly Barret'
          git config --global user.email 'Nelly-Barret@users.noreply.github.com'
          git add *.pdf
          git commit -m "Automated CV generation"
          git push
